// Раунд 2б: карточка схрона, черта «ближний бой» в Лесу, цель с направлением.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const pg = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; pg.on('console', m => { if (m.type() === 'error') errs.push(m.text()); }); pg.on('pageerror', e => errs.push('PAGEERR ' + e.message));
await pg.goto('http://localhost:8123/index.html?nosdk=1');
await pg.waitForSelector('#titleBtns button'); await pg.click('#titleBtns button'); await pg.waitForSelector('.class-card'); await pg.click('.class-card');
await pg.waitForFunction(() => window.__G && window.__G.zoneReady, null, { timeout: 60000 }); await pg.waitForTimeout(1200);
await pg.evaluate(() => { for (const b of document.querySelectorAll('button')) if (b.textContent.includes('опытный')) b.click(); });
const J = f => pg.evaluate(f);
await J(() => { const P = __G.profile; P.wild = { hints: { enter: 1, nemesis: 1 }, forest: { best: 0, depth: 0, stat: {}, claimed: {}, mem: { melee: 14, ranged: 2, deaths: 0, greedy: 2 } } }; });
await J(async () => { const G = __G; document.querySelectorAll('.modal-bg').forEach(e => e.remove()); G.modalOpen = false; G.paused = false; G.profile.level = 12; G.profile.tutorial.prologue = true;
  const m = await import('/js/game/game.js'); await m.loadZone('wild', { realm: 'forest', depth: 2 }); G.stats = (await import('/js/game/stats.js')).stats(G.profile); });
await pg.waitForTimeout(4000);
console.log('traits', JSON.stringify(await J(() => __G.wild.mem.map(t => t.id))), 'cacheLabel', await J(() => __G.zone.inter.find(i => i.type === 'cache').label));
await J(async () => { const m = await import('/js/game/loot.js'); for (let i = 0; i < 12; i++) m.dropGold(__G.player.x, __G.player.y, 25); });
await pg.waitForTimeout(1800); await pg.screenshot({ path: 'shots/r2b_hint.png' });
console.log('card', await J(() => document.body.innerText.match(/Схрон ▣[^]*?Понятно/)?.[0]?.replace(/\n/g, ' | ')));
console.log('goal', await J(() => document.body.innerText.match(/🎒 Ноша тяжёлая[^\n]*/)?.[0]));
console.log('errors', errs); await b.close();
